#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hello_index:
  path: /hello
  controller: App\Controller\HelloController::index
  defaults:
    name: 'hej'

recipe_index:
  path: /recipe
  controller: App\Controller\RecipeController::index

category_index:
  path: /category
  controller: App\Controller\CategoryController::index

comment_index:
  path: /comment
  controller: App\Controller\CommentController::index

recipe_show:
  path: /recipe/show/{id}
  controller: App\Controller\RecipeController::show

category_show:
  path: /category/show/{id}
  controller: App\Controller\CategoryController::show

comment_show:
  path: /comment/show/{id}
  controller: App\Controller\CommentController::show

category_create:
  path: /category/create
  controller: App\Controller\CategoryController::create

recipe_create:
  path: /recipe/create
  controller: App\Controller\RecipeController::create